drop extension if exists "pg_net";

alter table "public"."ghl_opportunities" drop constraint "ghl_opportunities_opportunity_id_key";

drop index if exists "public"."ghl_opportunities_opportunity_id_key";


  create table "public"."ghl_integrations" (
    "location_id" text not null,
    "access_token" text not null,
    "refresh_token" text not null,
    "expires_at" timestamp with time zone not null,
    "updated_at" timestamp with time zone default CURRENT_TIMESTAMP
      );


alter table "public"."ghl_opportunities" alter column "created_at" set not null;

alter table "public"."ghl_opportunities" alter column "id" drop default;

alter table "public"."ghl_opportunities" alter column "id" add generated by default as identity;

alter table "public"."ghl_opportunities" alter column "opportunity_id" drop not null;

alter table "public"."job_drafts" drop column "budget_max";

alter table "public"."job_drafts" drop column "budget_min";

alter table "public"."job_drafts" drop column "skills";

alter table "public"."job_drafts" drop column "status";

alter table "public"."job_drafts" add column "budget" text;

alter table "public"."job_drafts" add column "category" text;

alter table "public"."job_drafts" add column "key_features" text;

alter table "public"."job_drafts" add column "potential_challenges" text;

alter table "public"."job_drafts" add column "success_criteria" text;

alter table "public"."job_drafts" add column "target_audience" text;

alter table "public"."job_drafts" add column "technology_stack" text;

alter table "public"."job_drafts" alter column "id" drop default;

alter table "public"."job_drafts" alter column "id" add generated always as identity;

alter table "public"."job_drafts" alter column "timeline" set data type text using "timeline"::text;

alter table "public"."job_drafts" alter column "title" set not null;

alter table "public"."job_drafts" alter column "title" set data type text using "title"::text;

alter table "public"."trending_topics" disable row level security;

drop sequence if exists "public"."ghl_opportunities_id_seq";

drop sequence if exists "public"."job_drafts_id_seq";

CREATE UNIQUE INDEX ghl_integrations_pkey ON public.ghl_integrations USING btree (location_id);

alter table "public"."ghl_integrations" add constraint "ghl_integrations_pkey" PRIMARY KEY using index "ghl_integrations_pkey";

grant delete on table "public"."ghl_integrations" to "anon";

grant insert on table "public"."ghl_integrations" to "anon";

grant references on table "public"."ghl_integrations" to "anon";

grant select on table "public"."ghl_integrations" to "anon";

grant trigger on table "public"."ghl_integrations" to "anon";

grant truncate on table "public"."ghl_integrations" to "anon";

grant update on table "public"."ghl_integrations" to "anon";

grant delete on table "public"."ghl_integrations" to "authenticated";

grant insert on table "public"."ghl_integrations" to "authenticated";

grant references on table "public"."ghl_integrations" to "authenticated";

grant select on table "public"."ghl_integrations" to "authenticated";

grant trigger on table "public"."ghl_integrations" to "authenticated";

grant truncate on table "public"."ghl_integrations" to "authenticated";

grant update on table "public"."ghl_integrations" to "authenticated";

grant delete on table "public"."ghl_integrations" to "service_role";

grant insert on table "public"."ghl_integrations" to "service_role";

grant references on table "public"."ghl_integrations" to "service_role";

grant select on table "public"."ghl_integrations" to "service_role";

grant trigger on table "public"."ghl_integrations" to "service_role";

grant truncate on table "public"."ghl_integrations" to "service_role";

grant update on table "public"."ghl_integrations" to "service_role";


