-- Add is_ai_generated field to questions table for AI community member service
ALTER TABLE "public"."questions" 
ADD COLUMN IF NOT EXISTS "is_ai_generated" boolean DEFAULT false;

-- Create index for AI-generated questions
CREATE INDEX "idx_questions_is_ai_generated" ON "public"."questions" USING "btree" ("is_ai_generated");

-- Add comment for the new column
COMMENT ON COLUMN "public"."questions"."is_ai_generated" IS 'Indicates if this question was generated by AI community members';
